import { useQuery } from "@tanstack/react-query";
import type { FileDefinition, GraphNode } from "@codinflow/graph-schema";
import { api, type NodeDetail } from "./api";

interface InspectorProps {
  repositoryId: string;
  commitSha: string;
  nodeId: string | null;
  onSelectNode: (nodeId: string) => void;
  onOpenCode: (node: GraphNode) => void;
  onClose: () => void;
}

const EVIDENCE_LABEL: Record<string, string> = {
  syntactic: "Proven from syntax",
  semantic: "Proven by the type checker",
  framework_inferred: "Inferred from framework patterns",
  ai_generated: "Generated by AI — verify",
};

export function Inspector({ repositoryId, commitSha, nodeId, onSelectNode, onOpenCode, onClose }: InspectorProps) {
  const { data, isLoading, error } = useQuery({
    queryKey: ["node", repositoryId, commitSha, nodeId],
    queryFn: () => api.node(repositoryId, nodeId!, commitSha),
    enabled: Boolean(nodeId),
  });

  if (!nodeId) {
    return (
      <aside className="inspector empty">
        <p className="muted small pad">Select a file or a function to inspect it.</p>
      </aside>
    );
  }

  return (
    <aside className="inspector">
      <header>
        <h2>Inspector</h2>
        <div className="header-actions">
          {data?.node.filePath && (
            <button type="button" className="icon-button" title="Open source" onClick={() => onOpenCode(data.node)}>
              {"</>"}
            </button>
          )}
          <button type="button" onClick={onClose} aria-label="Close inspector">
            ✕
          </button>
        </div>
      </header>

      {isLoading && <p className="muted small pad">Loading…</p>}
      {error && <p className="error pad">{String(error)}</p>}

      {data &&
        (data.node.kind === "file" ? (
          <FileDetail detail={data} onSelectNode={onSelectNode} onOpenCode={onOpenCode} />
        ) : (
          <SymbolDetail detail={data} onSelectNode={onSelectNode} onOpenCode={onOpenCode} />
        ))}
    </aside>
  );
}

/** A file: what it defines, what it pulls in, what it hands out. */
function FileDetail({
  detail,
  onSelectNode,
  onOpenCode,
}: {
  detail: NodeDetail;
  onSelectNode: (id: string) => void;
  onOpenCode: (node: GraphNode) => void;
}) {
  const { node, incoming, outgoing } = detail;
  const definitions = (node.metadata?.definitions as FileDefinition[] | undefined) ?? [];
  const imports = (node.metadata?.imports as string[] | undefined) ?? [];
  const lineCount = node.metadata?.lineCount as number | undefined;
  const importedBy = incoming.filter((entry) => entry.edge.kind === "imports");
  const dependsOn = outgoing.filter((entry) => entry.edge.kind === "depends_on");

  return (
    <div className="inspector-body">
      <h3>{node.name}</h3>
      <p className="kind-line">file{lineCount ? ` · ${lineCount} lines` : ""}</p>
      <p className="mono tiny muted">{node.filePath}</p>

      <button type="button" className="wide-button" onClick={() => onOpenCode(node)}>
        {"</>"} View source
      </button>

      <Section title={`Definitions (${definitions.length})`}>
        {definitions.length === 0 ? (
          <p className="muted small">No module-level definitions.</p>
        ) : (
          <ul className="plain definitions-list">
            {definitions.map((definition) => (
              <li key={`${definition.name}:${definition.line}`}>
                <span className={`kw kw-${definition.keyword}`}>{definition.keyword}</span>
                <span className="def-name">{definition.name}</span>
                {definition.typeText && <span className="muted tiny mono"> {definition.typeText}</span>}
                {definition.exported && <span className="def-export">export</span>}
                <span className="muted tiny">:{definition.line}</span>
              </li>
            ))}
          </ul>
        )}
      </Section>

      <Section title={`Imports (${imports.length})`}>
        <ul className="plain mono tiny">
          {imports.map((specifier) => (
            <li key={specifier} className="muted">
              {specifier}
            </li>
          ))}
          {imports.length === 0 && <li className="muted">None</li>}
        </ul>
      </Section>

      <RelationList title="Imported by" entries={importedBy} onSelectNode={onSelectNode} />
      <RelationList title="Depends on" entries={dependsOn} onSelectNode={onSelectNode} />
    </div>
  );
}

/** A function, method or class: what it does, touches, and who depends on it. */
function SymbolDetail({
  detail,
  onSelectNode,
  onOpenCode,
}: {
  detail: NodeDetail;
  onSelectNode: (id: string) => void;
  onOpenCode: (node: GraphNode) => void;
}) {
  const { node, incoming, outgoing } = detail;

  const databaseAccess = outgoing.filter((entry) => entry.node?.kind === "database");
  const externalCalls = outgoing.filter((entry) => entry.node?.kind === "external_api");
  const errors = outgoing.filter((entry) => entry.edge.kind === "throws");
  const envReads = outgoing.filter((entry) => entry.node?.kind === "environment_variable");
  const calls = outgoing.filter((entry) => ["calls", "awaits"].includes(entry.edge.kind));
  const callers = incoming.filter((entry) => ["calls", "awaits", "routes_to", "runs_before"].includes(entry.edge.kind));
  const exported = node.visibility === "public" || node.metadata?.exported === true;

  return (
    <div className="inspector-body">
      <h3>{node.name}</h3>
      <p className="kind-line">
        {node.kind.replace(/_/g, " ")}
        {node.frameworkRole ? ` · ${node.frameworkRole}` : ""}
        {exported && <span className="def-export">exported</span>}
      </p>

      {node.signature && <pre className="signature">{node.signature}</pre>}

      {node.filePath && (
        <button type="button" className="wide-button" onClick={() => onOpenCode(node)}>
          {"</>"} View source
          {node.source ? ` · ${node.filePath.split("/").pop()}:${node.source.startLine}` : ""}
        </button>
      )}

      {node.summary ? <p className="summary">{node.summary}</p> : <AiExplainTeaser name={node.name} />}

      {/* What this function actually touches — the reviewer's first question. */}
      <RelationList title="Writes / reads data" entries={databaseAccess} onSelectNode={onSelectNode} />
      <RelationList title="Calls external services" entries={externalCalls} onSelectNode={onSelectNode} />
      <RelationList title="Throws" entries={errors} onSelectNode={onSelectNode} />
      <RelationList title="Reads environment" entries={envReads} onSelectNode={onSelectNode} />
      <UsedBy callers={callers} exported={exported} onSelectNode={onSelectNode} />
      <RelationList title="Calls" entries={calls} onSelectNode={onSelectNode} />

      {node.tags.length > 0 && (
        <Section title="Tags">
          <div className="tags">
            {node.tags.map((tag) => (
              <span key={tag} className={`tag tag-${tag}`}>
                {tag.replace(/-/g, " ")}
              </span>
            ))}
          </div>
        </Section>
      )}

      <Section title="Evidence">
        <p className="small">
          {EVIDENCE_LABEL[node.provenance.evidenceType] ?? node.provenance.evidenceType} · confidence{" "}
          {Math.round(node.analysisConfidence * 100)}%
        </p>
        <p className="muted tiny">
          {node.filePath}
          {node.source ? `:${node.source.startLine}-${node.source.endLine}` : ""} · {node.provenance.analyzer} v
          {node.provenance.analyzerVersion}
        </p>
      </Section>

      {node.tags.includes("unresolved-dynamic-call") && (
        <p className="warning small">
          This function contains a call the type checker could not resolve. Its outgoing edges may be incomplete.
        </p>
      )}
    </div>
  );
}

/**
 * Which files use this symbol, grouped by the file the call sites live in — the
 * traversal question "where is this used?". For an exported symbol, any file
 * that calls it must import it, so we title it "Imported by"; otherwise "Used by".
 * These are resolved call sites, so completeness tracks the analyzer's
 * resolved-call ratio (surfaced in the Application panel).
 */
function UsedBy({
  callers,
  exported,
  onSelectNode,
}: {
  callers: NodeDetail["incoming"];
  exported: boolean;
  onSelectNode: (id: string) => void;
}) {
  if (callers.length === 0) return null;

  const byFile = new Map<string, NodeDetail["incoming"]>();
  for (const entry of callers) {
    const file = entry.node?.filePath ?? entry.edge.sourceLocation?.filePath ?? "unknown";
    const list = byFile.get(file) ?? [];
    list.push(entry);
    byFile.set(file, list);
  }

  const title = exported ? "Imported by" : "Used by";

  return (
    <Section title={`${title} (${byFile.size} file${byFile.size === 1 ? "" : "s"})`}>
      <div className="used-by">
        {[...byFile.entries()].map(([file, entries]) => {
          // Clicking the file jumps to the first call site in it.
          const first = entries.find((entry) => entry.node)?.node;
          return (
            <div key={file} className="used-by-group">
              <button
                type="button"
                className="used-by-file link"
                title={`${file} — go to usage`}
                disabled={!first}
                onClick={() => first && onSelectNode(first.id)}
              >
                {file.split("/").pop()}
                <span className="muted tiny"> · {entries.length}</span>
              </button>
              <ul className="relations">
                {entries.map((entry) => (
                  <li key={entry.edge.id}>
                    <button type="button" onClick={() => entry.node && onSelectNode(entry.node.id)}>
                      {entry.node?.name ?? "unknown"}
                    </button>
                    {entry.edge.sourceLocation && (
                      <span className="muted mono tiny">:{entry.edge.sourceLocation.line}</span>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          );
        })}
      </div>
    </Section>
  );
}

function RelationList({
  title,
  entries,
  onSelectNode,
}: {
  title: string;
  entries: NodeDetail["outgoing"];
  onSelectNode: (id: string) => void;
}) {
  if (entries.length === 0) return null;

  return (
    <Section title={`${title} (${entries.length})`}>
      <ul className="relations">
        {entries.map((entry) => (
          <li key={entry.edge.id}>
            <button type="button" onClick={() => entry.node && onSelectNode(entry.node.id)}>
              {entry.node?.name ?? "unknown"}
            </button>
            {entry.edge.condition && (
              <code className="condition" title="Exact source condition">
                {entry.edge.condition}
              </code>
            )}
            {entry.edge.sourceLocation && (
              <span className="muted mono tiny">
                {entry.edge.sourceLocation.filePath}:{entry.edge.sourceLocation.line}
              </span>
            )}
          </li>
        ))}
      </ul>
    </Section>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="inspector-section">
      <h4>{title}</h4>
      {children}
    </section>
  );
}

/**
 * Placeholder for the Pro AI explanation. Everything here is free today; this
 * signals the paid direction without locking anything a user can currently do.
 */
function AiExplainTeaser({ name }: { name: string }) {
  return (
    <div className="ai-teaser">
      <div className="ai-teaser-head">
        <span className="ai-spark" aria-hidden="true">
          ✦
        </span>
        <span>Explain this code</span>
        <span className="pro-pill">Pro · soon</span>
      </div>
      <p className="muted small">
        A plain-English summary of what <code>{name}</code> does, generated from the analyzed facts above — never
        invented, always traceable to source.
      </p>
    </div>
  );
}
